name: GitHub Stats

on:
  schedule:
    - cron: '0 3 * * *'   # generate daily at 03:00 UTC
  workflow_dispatch:       # allow manual runs from Actions tab

jobs:
  stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Generate the user stats image
        uses: cicirello/user-statistician@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: Languages card
        uses: cicirello/user-statistician@v1
        with:
          image-file: images/languages.svg
          hide-keys: general, contributions, repositories
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Contributions + repos card
        uses: cicirello/user-statistician@v1
        with:
          image-file: images/userstats.svg
          hide-keys: languages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
